const nodes = [
  {
    id: "r_q9FSJRPtUypnXyn3",
    name: "全流量套餐-99",
    color: "1",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_1NAN4U0al9L86AZd",
    name: "0元0分钟",
    color: "1",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_kCfruXVtmrdHWPuj",
    name: "0元3G",
    color: "1",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_8IDHQyh03s3ztXXy",
    name: "99元档",
    color: "1",
    size: 38,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_lGjGe7uEmkG574J4",
    name: "电视",
    color: "1",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_DPzFSUpdUIDjJHxk",
    name: "宽带",
    color: "1",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_9Sjj4noBUDr9EfMG",
    name: "全屋WiFi-产品",
    color: "1",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_5qXzAApelYHrfyi0",
    name: "手机-副卡",
    color: "1",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_NQ25ZHmHGtSTvvSX",
    name: "手机-主卡",
    color: "1",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_qNFRVwDD9562dTGD",
    name: "智能家居-产品",
    color: "1",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
];
const links = [
  {
    hide: false,
    id: "-126187458681314",
    label: "包含产品（数量0~10）",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_q9FSJRPtUypnXyn3",
    target: "r_qNFRVwDD9562dTGD",
    value: 1,
  },
  {
    hide: false,
    id: "-313250569540511",
    label: "包含产品（数量0~10）",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_q9FSJRPtUypnXyn3",
    target: "r_9Sjj4noBUDr9EfMG",
    value: 1,
  },
  {
    hide: false,
    id: "733410300265539",
    label: "资费",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_q9FSJRPtUypnXyn3",
    target: "r_8IDHQyh03s3ztXXy",
    value: 1,
  },
  {
    hide: false,
    id: "517943437112179",
    label: "包含产品（数量0~3）",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_q9FSJRPtUypnXyn3",
    target: "r_5qXzAApelYHrfyi0",
    value: 1,
  },
  {
    hide: false,
    id: "532610830727310",
    label: "包含产品（数量0~1）",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_q9FSJRPtUypnXyn3",
    target: "r_DPzFSUpdUIDjJHxk",
    value: 1,
  },
  {
    hide: false,
    id: "578005284365320",
    label: "包含产品（数量1）",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_q9FSJRPtUypnXyn3",
    target: "r_NQ25ZHmHGtSTvvSX",
    value: 1,
  },
  {
    hide: false,
    id: "415142189534016",
    label: "包含产品（数量0~1）",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_q9FSJRPtUypnXyn3",
    target: "r_lGjGe7uEmkG574J4",
    value: 1,
  },
  {
    hide: false,
    id: "636686330984219",
    label: "套内流量",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_q9FSJRPtUypnXyn3",
    target: "r_kCfruXVtmrdHWPuj",
    value: 1,
  },
  {
    hide: false,
    id: "-861235521465270",
    label: "套内语音",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_q9FSJRPtUypnXyn3",
    target: "r_1NAN4U0al9L86AZd",
    value: 1,
  },
];

