const nodes = [
  {
    id: "r_vUhgXernRPXtXfgq",
    name: "阿司匹林",
    color: 4,
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_Z3pHNEJknaOvj1RK",
    name: "鼻咽炎药物治疗",
     color: "4",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_tUHhNCI8FII3bJM4",
    name: "不稳定性心绞痛药物治疗",
     color: "4",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_Don4w45LvYOjhLGu",
    name: "胆道蛔虫症药物治疗",
     color: "4",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_wGduuohpPqBq7KbB",
    name: "动静脉瘘药物治疗",
     color: "4",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_RT7AacoqXhotqFXy",
    name: "动脉粥样硬化药物治疗",
     color: "4",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_TcOi9CStL9nz6uqb",
    name: "发热药物治疗",
     color: "4",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_eqtgTEH603VrKlmY",
    name: "风湿热药物治疗",
     color: "4",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_qUjYh7FHcXwV3JjU",
    name: "风湿性关节炎药物治疗",
     color: "4",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_7hfufrPHWBCbdaWc",
    name: "腹泻药物治疗",
     color: "4",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_8j0FbAIiTMHnzVjW",
    name: "巩膜炎药物治疗",
     color: "4",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_fAr3QLeZji8f7wHy",
    name: "关节痛药物治疗",
     color: "4",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_CGx5gxsj58Qve6zT",
    name: "骨关节炎药物治疗",
     color: "4",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_gSEG9S3Ba1tkhHt6",
    name: "骨性关节炎药物治疗",
     color: "4",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_SA39qZc0p6LOY2zG",
    name: "虹膜睫状体炎药物治疗",
     color: "4",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_KKxNiJufovT4Mc0u",
    name: "蛔虫病药物治疗",
     color: "4",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_kVngXeIfeUtT3ZpX",
    name: "肌肉痛药物治疗",
     color: "4",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_ngRT4rZGNfOKQDRS",
    name: "脊柱炎药物治疗",
     color: "4",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_0L3F2qNYz4lZbHDz",
    name: "流行性感冒药物治疗",
     color: "4",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_7qPaHC09accQC3IO",
    name: "慢性稳定性心绞痛药物治疗",
     color: "4",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_pHA1jcI40oTi7LSY",
    name: "慢性心房颤动药物治疗",
     color: "4",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_N8QEsuXkIqPMkxbH",
    name: "脑缺血药物治疗",
     color: "4",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_ZOVBoGL5iYAWS8bb",
    name: "偏头痛药物治疗",
     color: "4",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_dLRPdmZH0vqXL8OJ",
    name: "普通感冒药物治疗",
     color: "4",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_35PEjOzbEvoB0Q5f",
    name: "强直性脊柱炎药物治疗",
     color: "4",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_KVuC0ZQ6zmt2fZgQ",
    name: "缺血性心脏病药物治疗",
     color: "4",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_WAYtQVEXG5YsE157",
    name: "神经痛药物治疗",
     color: "4",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_NOtNKTBGU1jCWSWR",
    name: "湿热药物治疗",
     color: "4",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_Cdors926MTa0hhUn",
    name: "疼痛药物治疗",
     color: "4",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_ThPmZ8Mp3tg5Zkuw",
    name: "痛风药物治疗",
     color: "4",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_MsNgXUBmGUFhC7Lh",
    name: "痛经药物治疗",
     color: "4",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_z69uHxBKzxyMhTNO",
    name: "头痛药物治疗药物治疗",
     color: "4",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_jowhwBHEd92pEkld",
    name: "心绞痛药物治疗",
     color: "4",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_PeNTSzJ9g3GRDDzU",
    name: "心肌梗死药物治疗",
     color: "4",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_MiyRP4gToZrz7Kah",
    name: "心肌炎药物治疗",
     color: "4",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_AwA4DUwifgkQfKhm",
    name: "心脏疾病药物治疗",
     color: "4",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_c7RBrDl3aPlFYXML",
    name: "血管炎药物治疗",
     color: "4",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_KvkR8WAU1zNh2Fql",
    name: "血栓形成药物治疗",
     color: "4",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_N0i0jJ3874hu2yaI",
    name: "咽炎药物治疗",
     color: "4",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_fohyx4exQ9q56UeH",
    name: "牙痛药物治疗",
     color: "4",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_C3U61ngLn31gnaea",
    name: "脂性渐进性坏死药物治疗",
     color: "4",
    size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
];
const links = [
  {
    hide: false,
    id: "380020086133596",
    label: "药物治疗项",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_NOtNKTBGU1jCWSWR",
    target: "r_vUhgXernRPXtXfgq",
    value: 1,
  },
  {
    hide: false,
    id: "74001686870731",
    label: "药物治疗项",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_CGx5gxsj58Qve6zT",
    target: "r_vUhgXernRPXtXfgq",
    value: 1,
  },
  {
    hide: false,
    id: "734453891513843",
    label: "药物治疗项",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_kVngXeIfeUtT3ZpX",
    target: "r_vUhgXernRPXtXfgq",
    value: 1,
  },
  {
    hide: false,
    id: "-869638473346980",
    label: "药物治疗项",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_8j0FbAIiTMHnzVjW",
    target: "r_vUhgXernRPXtXfgq",
    value: 1,
  },
  {
    hide: false,
    id: "571737171007180",
    label: "药物治疗项",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_TcOi9CStL9nz6uqb",
    target: "r_vUhgXernRPXtXfgq",
    value: 1,
  },
  {
    hide: false,
    id: "-738789439517184",
    label: "药物治疗项",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_ZOVBoGL5iYAWS8bb",
    target: "r_vUhgXernRPXtXfgq",
    value: 1,
  },
  {
    hide: false,
    id: "-642404519033188",
    label: "药物治疗项",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_KvkR8WAU1zNh2Fql",
    target: "r_vUhgXernRPXtXfgq",
    value: 1,
  },
  {
    hide: false,
    id: "65924373522085",
    label: "药物治疗项",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_7qPaHC09accQC3IO",
    target: "r_vUhgXernRPXtXfgq",
    value: 1,
  },
  {
    hide: false,
    id: "-217856899628329",
    label: "药物治疗项",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_PeNTSzJ9g3GRDDzU",
    target: "r_vUhgXernRPXtXfgq",
    value: 1,
  },
  {
    hide: false,
    id: "361616286040188",
    label: "药物治疗项",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_Don4w45LvYOjhLGu",
    target: "r_vUhgXernRPXtXfgq",
    value: 1,
  },
  {
    hide: false,
    id: "-498721933175911",
    label: "药物治疗项",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_pHA1jcI40oTi7LSY",
    target: "r_vUhgXernRPXtXfgq",
    value: 1,
  },
  {
    hide: false,
    id: "-840561722143097",
    label: "药物治疗项",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_fohyx4exQ9q56UeH",
    target: "r_vUhgXernRPXtXfgq",
    value: 1,
  },
  {
    hide: false,
    id: "895400936452603",
    label: "药物治疗项",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_jowhwBHEd92pEkld",
    target: "r_vUhgXernRPXtXfgq",
    value: 1,
  },
  {
    hide: false,
    id: "-228622578299172",
    label: "药物治疗项",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_N0i0jJ3874hu2yaI",
    target: "r_vUhgXernRPXtXfgq",
    value: 1,
  },
  {
    hide: false,
    id: "289859201347527",
    label: "药物治疗项",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_35PEjOzbEvoB0Q5f",
    target: "r_vUhgXernRPXtXfgq",
    value: 1,
  },
  {
    hide: false,
    id: "-713300279957806",
    label: "药物治疗项",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_7hfufrPHWBCbdaWc",
    target: "r_vUhgXernRPXtXfgq",
    value: 1,
  },
  {
    hide: false,
    id: "547354712205217",
    label: "药物治疗项",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_SA39qZc0p6LOY2zG",
    target: "r_vUhgXernRPXtXfgq",
    value: 1,
  },
  {
    hide: false,
    id: "-891367377871999",
    label: "药物治疗项",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_C3U61ngLn31gnaea",
    target: "r_vUhgXernRPXtXfgq",
    value: 1,
  },
  {
    hide: false,
    id: "-464956346603874",
    label: "药物治疗项",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_c7RBrDl3aPlFYXML",
    target: "r_vUhgXernRPXtXfgq",
    value: 1,
  },
  {
    hide: false,
    id: "-24619441885459",
    label: "药物治疗项",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_Z3pHNEJknaOvj1RK",
    target: "r_vUhgXernRPXtXfgq",
    value: 1,
  },
  {
    hide: false,
    id: "496191249541824",
    label: "药物治疗项",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_eqtgTEH603VrKlmY",
    target: "r_vUhgXernRPXtXfgq",
    value: 1,
  },
  {
    hide: false,
    id: "555395349550529",
    label: "药物治疗项",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_KKxNiJufovT4Mc0u",
    target: "r_vUhgXernRPXtXfgq",
    value: 1,
  },
  {
    hide: false,
    id: "-62655047283152",
    label: "药物治疗项",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_WAYtQVEXG5YsE157",
    target: "r_vUhgXernRPXtXfgq",
    value: 1,
  },
  {
    hide: false,
    id: "556441019047799",
    label: "药物治疗项",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_gSEG9S3Ba1tkhHt6",
    target: "r_vUhgXernRPXtXfgq",
    value: 1,
  },
  {
    hide: false,
    id: "145052201113647",
    label: "药物治疗项",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_Cdors926MTa0hhUn",
    target: "r_vUhgXernRPXtXfgq",
    value: 1,
  },
  {
    hide: false,
    id: "-485993206755163",
    label: "药物治疗项",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_MiyRP4gToZrz7Kah",
    target: "r_vUhgXernRPXtXfgq",
    value: 1,
  },
  {
    hide: false,
    id: "468167570568411",
    label: "药物治疗项",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_fAr3QLeZji8f7wHy",
    target: "r_vUhgXernRPXtXfgq",
    value: 1,
  },
  {
    hide: false,
    id: "265741395812513",
    label: "药物治疗项",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_AwA4DUwifgkQfKhm",
    target: "r_vUhgXernRPXtXfgq",
    value: 1,
  },
  {
    hide: false,
    id: "-778215680137098",
    label: "药物治疗项",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_0L3F2qNYz4lZbHDz",
    target: "r_vUhgXernRPXtXfgq",
    value: 1,
  },
  {
    hide: false,
    id: "351103802784204",
    label: "药物治疗项",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_MsNgXUBmGUFhC7Lh",
    target: "r_vUhgXernRPXtXfgq",
    value: 1,
  },
  {
    hide: false,
    id: "-26494616149384",
    label: "药物治疗项",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_N8QEsuXkIqPMkxbH",
    target: "r_vUhgXernRPXtXfgq",
    value: 1,
  },
  {
    hide: false,
    id: "-388947847640454",
    label: "药物治疗项",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_KVuC0ZQ6zmt2fZgQ",
    target: "r_vUhgXernRPXtXfgq",
    value: 1,
  },
  {
    hide: false,
    id: "707525741135154",
    label: "药物治疗项",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_ThPmZ8Mp3tg5Zkuw",
    target: "r_vUhgXernRPXtXfgq",
    value: 1,
  },
  {
    hide: false,
    id: "219494734107838",
    label: "药物治疗项",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_ngRT4rZGNfOKQDRS",
    target: "r_vUhgXernRPXtXfgq",
    value: 1,
  },
  {
    hide: false,
    id: "42900887463636",
    label: "药物治疗项",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_RT7AacoqXhotqFXy",
    target: "r_vUhgXernRPXtXfgq",
    value: 1,
  },
  {
    hide: false,
    id: "217890858064739",
    label: "药物治疗项",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_dLRPdmZH0vqXL8OJ",
    target: "r_vUhgXernRPXtXfgq",
    value: 1,
  },
  {
    hide: false,
    id: "-462196807339363",
    label: "药物治疗项",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_tUHhNCI8FII3bJM4",
    target: "r_vUhgXernRPXtXfgq",
    value: 1,
  },
  {
    hide: false,
    id: "523780458103615",
    label: "药物治疗项",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_z69uHxBKzxyMhTNO",
    target: "r_vUhgXernRPXtXfgq",
    value: 1,
  },
  {
    hide: false,
    id: "-633727407802600",
    label: "药物治疗项",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_wGduuohpPqBq7KbB",
    target: "r_vUhgXernRPXtXfgq",
    value: 1,
  },
  {
    hide: false,
    id: "-392147654979766",
    label: "药物治疗项",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_qUjYh7FHcXwV3JjU",
    target: "r_vUhgXernRPXtXfgq",
    value: 1,
  },
];
