const nodes = [
  {
    id: "r_KtOmTvVDQQkrGqRW",
    name: "CJ-HJ-SK-已计算费用开支",
    color: "2",
     size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_DXPfhotuifiwHmfz",
    name: "成都川能电力工程有限公司",
    color: "2",
     size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_cm3MwxhnKXyB2Yzo",
    name: "福建闽南电力公司",
    color: "2",
     size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_Grd1y58wgLccgmFS",
    name: "国网吉林省电力有限公司分公司",
    color: "2",
     size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_3XWIEeViAixfjb9F",
    name: "国网浙江新兴科技有限公司2022年第六批集中招标采购批次项目招标",
    color: "2",
     size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_jhq0VRXXAfsl0S5S",
    name: "华能国际电力股份有限公司",
    color: "2",
     size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_0rxO5fGSe2yxTd9S",
    name: "江苏川能电力实业有限公司",
    color: "2",
     size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_Bwx3gWzznAOUjRnI",
    name: "上海电力股份有限公司",
    color: "2",
     size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_2GM9YoE5VCKKCbf3",
    name: "孙志豪",
    color: "2",
     size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_7UZZdDs9JFrpNDcM",
    name: "云南文山电力股份有限公司",
    color: "2",
     size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
  {
    id: "r_0eQ9zeA38bTT4gsP",
    name: "浙江川能电力设备有限公司",
    color: "2",
     size: 2,
    shape: "circle",
    hide: false,
    isExtendedState: false,
  },
];
const links = [
  {
    hide: false,
    id: "544039305215961",
    label: "被审计单位",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_KtOmTvVDQQkrGqRW",
    target: "r_Bwx3gWzznAOUjRnI",
    value: 1,
  },
  {
    hide: false,
    id: "564193137425290",
    label: "被审计单位",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_KtOmTvVDQQkrGqRW",
    target: "r_7UZZdDs9JFrpNDcM",
    value: 1,
  },
  {
    hide: false,
    id: "701738721376589",
    label: "被审计单位",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_KtOmTvVDQQkrGqRW",
    target: "r_0eQ9zeA38bTT4gsP",
    value: 1,
  },
  {
    hide: false,
    id: "883304718902853",
    label: "编制人",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_KtOmTvVDQQkrGqRW",
    target: "r_2GM9YoE5VCKKCbf3",
    value: 1,
  },
  {
    hide: false,
    id: "-921671027904036",
    label: "被审计单位",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_KtOmTvVDQQkrGqRW",
    target: "r_jhq0VRXXAfsl0S5S",
    value: 1,
  },
  {
    hide: false,
    id: "-722404730639804",
    label: "被审计单位",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_KtOmTvVDQQkrGqRW",
    target: "r_0rxO5fGSe2yxTd9S",
    value: 1,
  },
  {
    hide: false,
    id: "-41254713704372",
    label: "被审计单位",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_KtOmTvVDQQkrGqRW",
    target: "r_DXPfhotuifiwHmfz",
    value: 1,
  },
  {
    hide: false,
    id: "295156419618482",
    label: "被审计单位",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_KtOmTvVDQQkrGqRW",
    target: "r_Grd1y58wgLccgmFS",
    value: 1,
  },
  {
    hide: false,
    id: "572487106680614",
    label: "关联项目",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_KtOmTvVDQQkrGqRW",
    target: "r_3XWIEeViAixfjb9F",
    value: 1,
  },
  {
    hide: false,
    id: "900313926976849",
    label: "被审计单位",
    props: [],
    sourceRadius: 32,
    targetRadius: 32,
    source: "r_KtOmTvVDQQkrGqRW",
    target: "r_cm3MwxhnKXyB2Yzo",
    value: 1,
  },
];
